/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIdIndexRouteImport } from './routes/employee/$id/index'
import { Route as EmployeeIdWorkDateRouteImport } from './routes/employee/$id/work/$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIdIndexRoute = EmployeeIdIndexRouteImport.update({
  id: '/employee/$id/',
  path: '/employee/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIdWorkDateRoute = EmployeeIdWorkDateRouteImport.update({
  id: '/employee/$id/work/$date',
  path: '/employee/$id/work/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee/$id': typeof EmployeeIdIndexRoute
  '/employee/$id/work/$date': typeof EmployeeIdWorkDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee/$id': typeof EmployeeIdIndexRoute
  '/employee/$id/work/$date': typeof EmployeeIdWorkDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee/$id/': typeof EmployeeIdIndexRoute
  '/employee/$id/work/$date': typeof EmployeeIdWorkDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employee/$id' | '/employee/$id/work/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee/$id' | '/employee/$id/work/$date'
  id: '__root__' | '/' | '/employee/$id/' | '/employee/$id/work/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeIdIndexRoute: typeof EmployeeIdIndexRoute
  EmployeeIdWorkDateRoute: typeof EmployeeIdWorkDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$id/': {
      id: '/employee/$id/'
      path: '/employee/$id'
      fullPath: '/employee/$id'
      preLoaderRoute: typeof EmployeeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$id/work/$date': {
      id: '/employee/$id/work/$date'
      path: '/employee/$id/work/$date'
      fullPath: '/employee/$id/work/$date'
      preLoaderRoute: typeof EmployeeIdWorkDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeIdIndexRoute: EmployeeIdIndexRoute,
  EmployeeIdWorkDateRoute: EmployeeIdWorkDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
